apiVersion: v1
kind: ConfigMap
metadata:
  name: database-init-scripts
  namespace: jobswipe
data:
  profile-init.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      email VARCHAR(255) UNIQUE NOT NULL,
      name VARCHAR(255) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS profiles (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id),
      title VARCHAR(255),
      skills TEXT[],
      experience_years INTEGER,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

  match-init.sql: |
    CREATE TABLE IF NOT EXISTS matches (
      id SERIAL PRIMARY KEY,
      job_seeker_id INTEGER NOT NULL,
      recruiter_id INTEGER NOT NULL,
      job_id INTEGER NOT NULL,
      status VARCHAR(50),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );