# k8s/services/profile-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  namespace: jobswipe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
      - name: profile-service
        image: jobswipe/profile-service:latest  # You'll need to replace this with your actual image
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: profile-db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: profile-db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: profile-db-password
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: jobswipe
spec:
  selector:
    app: profile-service
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP