apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jobswipe-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  encrypted: "true"
reclaimPolicy: Retain
allowVolumeExpansion: true